controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


create_user:
    path: /users
    controller: App\Controller\UserController::createUser
    methods: POST